In [1]:
from numpy import *
a = array([1 + 1j, 2, 3, 4])
a.dtype

dtype('complex128')

In [2]:
a.real

array([1., 2., 3., 4.])

In [3]:
a.imag

array([1., 0., 0., 0.])

In [4]:
a.imag = [1,2,3,4]
a

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [5]:
a.conj()

array([1.-1.j, 2.-2.j, 3.-3.j, 4.-4.j])

In [6]:
a = array([0.,1,2,3])
a.dtype

dtype('float64')

In [7]:
a.real

array([0., 1., 2., 3.])

In [8]:
a.imag

array([0., 0., 0., 0.])

In [9]:
a.conj()

array([0., 1., 2., 3.])

In [10]:
#虚部是只读的，并不能修改它的值
a.imag = [1,2,3,4]

TypeError: array does not have imaginary part to set

In [12]:
a = array([0,1.0,2,3])
a.dtype

dtype('float64')

In [13]:
a.nbytes

32

In [14]:
a = array([0,1.0,2,3],
         dtype=float32)
a.dtype

dtype('float32')

In [15]:
a.nbytes

16

In [16]:
a = array([0,1,2,3],
         dtype=uint8)
a.dtype

dtype('uint8')

In [17]:
a = array([102,111,212], 
          dtype=uint8)
a.tofile('foo.dat')

In [18]:
b = frombuffer('foo', 
               dtype=uint8)
b

AttributeError: 'str' object has no attribute '__buffer__'

In [19]:
import os
os.remove('foo.dat')

In [20]:
ord('f')

102

In [21]:
ord('S')

83

In [23]:
a = array([1,1.2,'hello', [10,20,30]], 
          dtype=object)
a * 2

array([2, 2.4, 'hellohello', list([10, 20, 30, 10, 20, 30])], dtype=object)

In [24]:
a = array([1.5, -3], 
         dtype=float32)
a

array([ 1.5, -3. ], dtype=float32)

In [25]:
asarray(a, dtype=float64)

array([ 1.5, -3. ])

In [26]:
asarray(a, dtype=uint8)

array([  1, 253], dtype=uint8)

In [27]:
a #asarray 不会修改原来数组的值

array([ 1.5, -3. ], dtype=float32)

In [28]:
b = asarray(a, dtype=float32)

In [29]:
b is a 

True

In [30]:
asarray([1,2,3,4])

array([1, 2, 3, 4])

In [31]:
a.astype(float64)

array([ 1.5, -3. ])

In [32]:
a.astype(uint8)

array([  1, 253], dtype=uint8)

In [33]:
a

array([ 1.5, -3. ], dtype=float32)

In [34]:
b = a.astype(float32)
print (a)
print (b)

[ 1.5 -3. ]
[ 1.5 -3. ]


In [35]:
a is b

False

In [36]:
a = array((1,2,3,4), dtype=int32)
a

array([1, 2, 3, 4])

In [37]:
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

In [38]:
a[0] = 2**30
a

array([1073741824,          2,          3,          4])

In [39]:
b

array([ 0,  0,  0, 64,  2,  0,  0,  0,  3,  0,  0,  0,  4,  0,  0,  0],
      dtype=uint8)