In [1]:
from numpy import *
lst = [0,1,2,3]
a = array(lst)
a

array([0, 1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
# 32比特的整数
a.dtype

dtype('int32')

In [4]:
a.itemsize

4

In [5]:
# 1维数组，返回一个元组
a.shape

(4,)

In [6]:
shape(a)

(4,)

In [7]:
lst = [1,2,3,4]
shape(lst)

(4,)

In [8]:
a.size

4

In [9]:
size(a)

4

In [10]:
a.nbytes

16

In [11]:
a.ndim

1

In [12]:
#使用fill方法设定初始值 可以使用 fill 方法将数组设为指定
a.fill(-4.8)
a

array([-4, -4, -4, -4])

In [13]:
#索引与切片
a = array([0, 1, 2, 3])
a[0]

0

In [14]:
a[0] = 10
a

array([10,  1,  2,  3])

In [15]:
a = array([11,12,13,14,15])
a[1:3]

array([12, 13])

In [16]:
a[1:-2]

array([12, 13])

In [17]:
a[-4:3]

array([12, 13])

In [18]:
a[::2]

array([11, 13, 15])

In [19]:
a[-2:]

array([14, 15])

In [20]:
od = array([21000, 21180, 21240, 22100, 22400])
dist = od[1:] - od[:-1]
dist

array([180,  60, 860, 300])

In [21]:
#多维数组
a = array([[ 0, 1, 2, 3],
           [10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [22]:
a.shape
#这里2代表行数，4代表列数

(2, 4)

In [23]:
# 查看元素个数 2 * 4 = 8
a.size

8

In [24]:
#查看维数
a.ndim

2

In [25]:
a[1, 3]

13

In [26]:
a[1, 3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [27]:
# 返回第二行元组组成的array
a[1]

array([10, 11, 12, -1])

In [28]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [29]:
a[0, 3:5]

array([3, 4])

In [30]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [31]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [32]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [34]:
a = array([0,1,2,3,4])
b = a[2:4]
print( b)

[2 3]


In [35]:
b[0] = 10
a

array([ 0,  1, 10,  3,  4])

In [36]:
a = [1,2,3,4,5]
b = a[2:3]
b[0] = 13234
a

[1, 2, 3, 4, 5]

In [37]:
a = array([0,1,2,3,4])
b = a[2:4].copy()
b[0] = 10
a

array([0, 1, 2, 3, 4])

In [38]:
a = arange(0, 80, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [39]:
indices = [1, 2, -3]
y = a[indices]
y

array([10, 20, 50])

In [42]:
mask = array([0,1,1,0,0,1,0,0],
            dtype=bool)
a[mask]

array([10, 20, 50])

In [43]:
from numpy.random import rand
a = rand(10)
a

array([7.98595492e-01, 5.13218500e-04, 9.27833121e-01, 1.44989640e-01,
       3.81016113e-01, 7.71406786e-01, 9.45035661e-01, 9.55916261e-01,
       4.59956987e-01, 1.80391398e-01])

In [44]:
mask = a > 0.5
a[mask]

array([0.79859549, 0.92783312, 0.77140679, 0.94503566, 0.95591626])

In [45]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [46]:
a[(0,1,2,3,4), (1,2,3,4,5)] #返回的是一条次对角线上的5个值

array([ 1, 12, 23, 34, 45])

In [47]:
 a[3:, [0,2,5]] #返回的是最后三行的第1，3，5列

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [48]:
mask = array([1,0,1,0,0,1],
            dtype=bool)
a[mask, 2] #使用mask进行索引

array([ 2, 22, 52])

In [49]:
#只给定行索引的时候，返回整行
y = a[:3]
y

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [51]:
condition = array([0,1,1,0,1],
                 dtype=bool)
a[condition]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5

In [52]:
a = arange(64)
a.shape = 4,4,4
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [53]:
y = a[:,:,[2, -1]]
y

array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [54, 55],
        [58, 59],
        [62, 63]]])

In [ ]:
#where语句
#where 函数会返回所有非零元素的索引

In [56]:
a = array([0, 12, 5, 20])
a > 10

array([False,  True, False,  True])

In [57]:
where(a > 10)

(array([1, 3], dtype=int64),)

In [58]:
indices = where(a > 10)
indices = indices[0]
indices

array([1, 3], dtype=int64)

In [59]:
indices = where(a>10)[0]
indices

array([1, 3], dtype=int64)

In [60]:
loc = where(a > 10)
a[loc]

array([12, 20])

In [62]:
a = array([[0, 12, 5, 20],
           [1, 2, 11, 15]])
loc = where(a > 10)
loc

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 2, 3], dtype=int64))

In [63]:
a[loc]

array([12, 20, 11, 15])

In [64]:
rows, cols = where(a>10)
rows

array([0, 0, 1, 1], dtype=int64)

In [65]:
cols

array([1, 3, 2, 3], dtype=int64)

In [66]:
a[rows, cols]

array([12, 20, 11, 15])

In [67]:
a = arange(25)
a.shape = 5,5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
a > 12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [69]:
where(a > 12)

(array([2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))