In [1]:
#使用 mat 方法将 2 维数组转化为矩阵
import numpy as np
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [2]:
#使用 Matlab 的语法传入一个字符串来生成矩阵
A = np.mat('1,2,4;2,5,3;7,8,9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [3]:
#利用分块创造新的矩阵
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [4]:
#矩阵与向量的乘法
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [5]:
A * x

matrix([[17],
        [21],
        [50]])

In [6]:
#A.I 表示 A 矩阵的逆矩阵
A * A.I

matrix([[1.00000000e+00, 5.55111512e-17, 0.00000000e+00],
        [0.00000000e+00, 1.00000000e+00, 2.08166817e-17],
        [2.22044605e-16, 4.16333634e-17, 1.00000000e+00]])

In [7]:
#阵指数表示矩阵连乘
A ** 4

matrix([[ 6497,  9580,  9836],
        [ 7138, 10561, 10818],
        [18434, 27220, 27945]])