In [1]:
import numpy as np
#hypot 返回对应点 (x,y) 到原点的距离
x = np.array([1,2,3])
y = np.array([4,5,6])
np.hypot(x,y)

array([4.12310563, 5.38516481, 6.70820393])

In [2]:
#正无穷
np.inf

inf

In [3]:
#负无穷
-np.inf

-inf

In [4]:
#非法值（Not a number）
np.nan

nan

In [5]:
#检查是否为无穷
np.isinf(1.0)

False

In [6]:
np.isinf(np.inf)

True

In [7]:
np.isinf(-np.inf)

True

In [8]:
np.array([0]) / 0.0 #不会报错，而是返回一个非法值

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([nan])

In [9]:
#只有 0/0 会得到 nan，非0值除以0会得到无穷
a = np.arange(5.0)
b = a / 0.0
b

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in true_divide
  app.launch_new_instance()
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: invalid value encountered in true_divide
  app.launch_new_instance()


array([nan, inf, inf, inf, inf])

In [10]:
#nan 与任何数进行比较都是 False
b == np.nan

array([False, False, False, False, False])

In [12]:
#想要找出 nan 值需要使用 isnan
np.isnan(b)

array([ True, False, False, False, False])