In [1]:
import numpy as np

a = np.array([11,21,31,12,22,32,13,23,33])
a.shape = 3,3
a

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [2]:
a.diagonal()

array([11, 22, 33])

In [3]:
a.diagonal(offset=1)

array([21, 32])

In [4]:
a.diagonal(offset=-1)

array([12, 23])

In [5]:
i = [0,1,2]
a[i, i]

array([11, 22, 33])

In [6]:
a[i, i] = 2
a

array([[ 2, 21, 31],
       [12,  2, 32],
       [13, 23,  2]])

In [7]:
i = np.array([0,1])
a[i, i + 1] = 1
a

array([[ 2,  1, 31],
       [12,  2,  1],
       [13, 23,  2]])

In [8]:
a[i + 1, i] = -1
a

array([[ 2,  1, 31],
       [-1,  2,  1],
       [13, -1,  2]])