In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
#sort函数 sort 返回的结果是从小到大排列的
names = array(['bob', 'sue', 'jan', 'ad'])
weights = array([20.8, 93.2, 53.4, 61.8])
sort(weights)

array([20.8, 53.4, 61.8, 93.2])

In [3]:
#argsort函数 argsort 返回从小到大的排列在数组中的索引位置
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int64)

In [4]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

In [5]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'], dtype='<U3')

In [6]:
weights

array([20.8, 93.2, 53.4, 61.8])

In [7]:
#数组也支持方法操作
data = array([20.8,  93.2,  53.4,  61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

In [8]:
data

array([20.8, 93.2, 53.4, 61.8])

In [9]:
data.sort()
data

array([20.8, 53.4, 61.8, 93.2])

In [10]:
#二维数组排序
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [11]:
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [12]:
sort(a, axis = 0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.7]])

In [ ]:
#searchsorted 函数
#searchsorted(sorted_array, values)
#searchsorted 接受两个参数，其中，第一个必需是已排序的数组

In [14]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

In [15]:
from numpy.random import rand
data = rand(100)
data.sort()
bounds = .4,.6
bounds

(0.4, 0.6)

In [17]:
low_idx, high_idx = searchsorted(data, bounds)
data[low_idx:high_idx]

array([0.41214482, 0.42980124, 0.43275909, 0.43967013, 0.44910725,
       0.45199292, 0.47641771, 0.49054116, 0.49204959, 0.49601236,
       0.50574515, 0.50833222, 0.52486595, 0.54826547, 0.54927383,
       0.55015769, 0.55900974, 0.56531741, 0.58075098])