In [1]:
%pylab

a = arange(6)
a

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


array([0, 1, 2, 3, 4, 5])

In [2]:
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [6]:
#使用 newaxis 增加数组维数
a = arange(3)
shape(a)

(3,)

In [7]:
y = a[newaxis, :]
shape(y)

(1, 3)

In [8]:
y = a[:, newaxis]
shape(y)

(3, 1)

In [9]:
y = a[newaxis, newaxis, :]
shape(y)

(1, 1, 3)

In [10]:
#squeeze 方法去除多余的轴
a = arange(6)
a.shape = (2,1,3)

In [11]:
b = a.squeeze()
b.shape

(2, 3)

In [12]:
#数组转置 使用 transpose 返回数组的转置，本质上是将所有维度反过来
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [13]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [14]:
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [15]:
a = arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [16]:
a.shape = 3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [17]:
b = a.T
b.shape

(5, 4, 3)

In [18]:
a = arange(6)
a.shape = (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
b = a.T
b[0,1] = 30
a

array([[ 0,  1,  2],
       [30,  4,  5]])

In [21]:
#数组连接

x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
print (x.shape)
print (y.shape)

(2, 3)
(2, 3)


In [22]:
z = concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [23]:
z.shape

(4, 3)

In [24]:
z = concatenate((x,y), axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [25]:
z.shape

(2, 6)

In [26]:
z = array((x,y))
z.shape

(2, 2, 3)

In [27]:
vstack((x, y)).shape

(4, 3)

In [28]:
hstack((x, y)).shape

(2, 6)

In [29]:
dstack((x, y)).shape

(2, 3, 2)

In [30]:
#Flatten数组 flatten 方法的作用是将多维数组转化为1维数组

a = array([[0,1],
           [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

In [31]:
b[0] = 10
print (b)
print (a)

[10  1  2  3]
[[0 1]
 [2 3]]


In [32]:
#flat 属性
a.flat

In [33]:
b = a.flat

In [34]:
b[0]

0

In [35]:
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

In [36]:
a.flat[:]

array([10,  1,  2,  3])

In [37]:
#ravel 方法
a = array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

In [38]:
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

In [39]:
a = array([[0,1],
           [2,3]])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [40]:
#atleast_xd 函数
x = 1
atleast_1d(x)

array([1])

In [41]:
a = array([1,2,3])
b = atleast_2d(a)
b.shape

(1, 3)

In [42]:
b

array([[1, 2, 3]])

In [43]:
c = atleast_3d(b)

In [44]:
c.shape

(1, 3, 1)