In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
a = array([[1,2,3], 
           [4,5,6]])

In [3]:
sum(a)

21

In [4]:
sum(a, axis=0)

array([5, 7, 9])

In [5]:
sum(a, axis=1)

array([ 6, 15])

In [6]:
sum(a, axis=-1)

array([ 6, 15])

In [7]:
a.sum()

21

In [8]:
a.sum(axis=0)

array([5, 7, 9])

In [9]:
a.sum(axis=-1)

array([ 6, 15])

In [10]:
a.prod()

720

In [11]:
prod(a, axis=0)

array([ 4, 10, 18])

In [12]:
from numpy.random import rand
a = rand(3, 4)
%precision 3
a

array([[0.14 , 0.496, 0.638, 0.52 ],
       [0.17 , 0.571, 0.292, 0.884],
       [0.635, 0.131, 0.371, 0.586]])

In [13]:
a.min()

0.131

In [14]:
a.min(axis=0)

array([0.14 , 0.131, 0.292, 0.52 ])

In [15]:
a.max()

0.884

In [16]:
a.max(axis=-1)

array([0.638, 0.884, 0.635])

In [17]:
a.argmin()

9

In [18]:
a.argmin(axis=0)

array([0, 2, 1, 0], dtype=int64)

In [19]:
a = array([[1,2,3],[4,5,6]])

In [20]:
a.mean()

3.500

In [21]:
a.mean(axis=-1)

array([2., 5.])

In [22]:
mean(a)

3.500

In [23]:
average(a, axis = 0)

array([2.5, 3.5, 4.5])

In [24]:
average(a, axis = 0, weights=[1,2])

array([3., 4., 5.])

In [25]:
a.std(axis=1)

array([0.816, 0.816])

In [26]:
a.var(axis=1)

array([0.667, 0.667])

In [27]:
var(a, axis=1)

array([0.667, 0.667])

In [28]:
std(a, axis=1)

array([0.816, 0.816])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

In [31]:
a.ptp(axis=1)

array([2, 2])

In [32]:
a.ptp()

5

In [33]:
a = array([1.35, 2.5, 1.5])

In [34]:
a.round()

array([1., 2., 2.])

In [35]:
a.round(decimals=1)

array([1.4, 2.5, 1.5])