In [1]:
import numpy as np
a = np.array([1,2])
#数组与标量相乘，相当于数组的每个元素乘以这个标量
a * 3

array([3, 6])

In [2]:
#数组逐元素相乘
a = np.array([1,2])
b = np.array([3,4])
a * b

array([3, 8])

In [3]:
#使用函数
np.multiply(a, b)

array([3, 8])

In [4]:
#函数还可以接受第三个参数，表示将结果存入第三个参数中
np.multiply(a, b, a)

array([3, 8])

In [5]:
a

array([3, 8])

In [6]:
#比较和逻辑运算

a = np.array([[1,2,3,4],
              [2,3,4,5]])
b = np.array([[1,2,5,4],
              [1,3,4,5]])
a == b

#要使用：if all(a==b)
#对于浮点数，由于存在精度问题，使用函数 allclose 

array([[ True,  True, False,  True],
       [False,  True,  True,  True]])

In [7]:
#logical_and 也是逐元素的 and 操作
a = np.array([0,1,2])
b = np.array([0,10,0])

np.logical_and(a, b)

array([False,  True, False])

In [8]:
#比特操作
a = np.array([1,2,4,8])
b = np.array([16,32,64,128])

a | b

array([ 17,  34,  68, 136], dtype=int32)

In [9]:
#取反
a = np.array([1,2,3,4], np.uint8)
~a

array([254, 253, 252, 251], dtype=uint8)

In [10]:
#左移
a << 3

array([ 8, 16, 24, 32], dtype=uint8)

In [11]:
# &的运算优先于比较运算如 > 等，所以必要时候需要加上括号

a = np.array([1,2,4,8])
b = np.array([16,32,64,128])

(a > 3) & (b < 100)

array([False, False,  True, False])